[project]
name = 'Urban-Air-Quality-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.air-quality-reports]
path = 'contracts/air-quality-reports.clar'
clarity_version = 2
epoch = 2.5

[contracts.incentive-system]
path = 'contracts/incentive-system.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-registry]
path = 'contracts/sensor-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
