[project]
name = 'Urban-Air-Quality-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
